name: Build and Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Cache node Modules'
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3
        with:
          path: ~.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build
        run: npm run build

      - name: Running Tests
        run: npm run test
